# Generated by Django 4.0.5 on 2022-09-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_podcastmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastermodel',
            name='slug',
            field=models.SlugField(default=123, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
