# Generated by Django 4.0.5 on 2022-09-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_contactmodel_alter_podcastmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
